# Generated by Django 3.2 on 2022-02-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('path', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=512)),
            ],
        ),
    ]
